config/routes.rb
Rails.application.routes.draw do
  resources :reports
  resources :datesheets
  resources :students do
    resources :reports
  end  
  resources :class_groups
  resources :teachers
  resources :timetables
  resources :adminforms
  resources :notices
  resources :events
  get 'home/home'
  get 'home/transport'
  get 'home/admission'
  get 'home/timetable' 
  get 'home/datesheet' 
  get 'home/teacher' 
  post 'home/timetable' => 'timetables#class_filter' , as: 'class_filter'
  post 'home/datesheet' => 'datesheets#datesheet_filter' , as: 'datesheet_filter'
  root 'home#home'
  get 'upload/index'
  get 'upload/uploadFile' 

  devise_for :users 

end

app/models/adminform.rb
class Adminform < ActiveRecord::Base
end

app/models/class_group.rb
class ClassGroup < ActiveRecord::Base
	belongs_to :student	
end

app/models/datafile.rb
class DataFile < ActiveRecord::Base
  def self.save(upload)
    name =  upload['datafile'].original_filename
    directory = "public/data"
    # create the file path
    path = File.join(directory, name)
    # write the file
    File.open(path, "wb") { |f| f.write(upload['datafile'].read) }
  end
end

app/models/datesheet.rb
class Datesheet < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/notice.rb
class Notice < ActiveRecord::Base
end

app/models/report.rb
class Report < ActiveRecord::Base
	belongs_to :student
end

app/models/student.rb
class Student < ActiveRecord::Base
	has_many :classgroups
	has_many :reports
	mount_uploader :stud_image, ImageUploader
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
	belongs_to :user
	validates :teacher_id, uniqueness: true
	has_attached_file :photo, :styles => { :small => "150x150>" }
    mount_uploader :image, ImageUploader 
	validates_attachment_content_type :photo, :content_type => ['image/jpg', 'image/png']
end

app/models/timetable.rb
class Timetable < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   GENDER_TYPES = [ ["Male","0"], [ "Female","1" ] ]
   validates_inclusion_of :is_female, in: [true, false]    
     
end

app/controllers/notices_controller.rb
class NoticesController < ApplicationController
  before_action :set_notice, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! , only: [:edit, :new, :destroy]

  # GET /notices
  # GET /notices.json
  def index
    @notices = Notice.all
  end

  # GET /notices/1
  # GET /notices/1.json
  def show
  end

  # GET /notices/new
  def new
    @notice = Notice.new
  end

  # GET /notices/1/edit
  def edit
  end

  # POST /notices
  # POST /notices.json
  def create
    @notice = Notice.new(notice_params)

    respond_to do |format|
      if @notice.save
          @user = current_user
          UserMailer.new_email(@user)
        format.html { redirect_to @notice, notice: 'Notice was successfully created.' }
        format.json { render :show, status: :created, location: @notice }
      else
        format.html { render :new }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notices/1
  # PATCH/PUT /notices/1.json
  def update
    respond_to do |format|
      if @notice.update(notice_params)
        format.html { redirect_to @notice, notice: 'Notice was successfully updated.' }
        format.json { render :show, status: :ok, location: @notice }
      else
        format.html { render :edit }
        format.json { render json: @notice.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notices/1
  # DELETE /notices/1.json
  def destroy
    @notice.destroy
    respond_to do |format|
      format.html { redirect_to notices_url, notice: 'Notice was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_notice
      @notice = Notice.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def notice_params
      params.require(:notice).permit(:titlt, :body)
    end
end

app/helpers/adminforms_helper.rb
module AdminformsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/datesheets_helper.rb
module DatesheetsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/timetables_helper.rb
module TimetablesHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/views/notices/_form.html.erb
<%= form_for(@notice) do |f| %>
  <% if @notice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notice.errors.count, "error") %> prohibited this notice from being saved:</h2>

      <ul>
      <% @notice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :titlt, "Title " %><br>
    <%= f.text_field :titlt %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notices/edit.html.erb
<h1>Editing Notice</h1>

<%= render 'form' %>

<%= link_to 'Show', @notice %> |
<%= link_to 'Back', notices_path %>

app/views/notices/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Notices</h1>

<table>
  <thead>
    <tr>
      <th>Titlt</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @notices.each do |notice| %>
      <tr>
        <td><%= notice.titlt %></td>
        <td><%= notice.body %></td>
        <td><%= link_to 'Show', notice %></td>
        <td><%= link_to 'Edit', edit_notice_path(notice) %></td>
        <td><%= link_to 'Destroy', notice, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Notice', new_notice_path %>

app/views/notices/new.html.erb
<h1>New Notice</h1>

<%= render 'form' %>

<%= link_to 'Back', notices_path %>

app/views/notices/show.html.erb
<p id="notice"><%= notice %></p>
<h1>Notice Board </h1>
<p>
  <strong>Titlt:</strong>
  <%= @notice.titlt %>
</p>

<p>
  <strong>Body:</strong>
  <%= @notice.body %>
</p>

<%= link_to 'Edit', edit_notice_path(@notice) %> |
<%= link_to 'Back', notices_path %>