config/routes.rb
Rails.application.routes.draw do
  resources :reports
  resources :datesheets
  resources :students do
    resources :reports
  end  
  resources :class_groups
  resources :teachers
  resources :timetables
  resources :adminforms
  resources :notices
  resources :events
  get 'home/home'
  get 'home/transport'
  get 'home/admission'
  get 'home/timetable' 
  get 'home/datesheet' 
  get 'home/teacher' 
  post 'home/timetable' => 'timetables#class_filter' , as: 'class_filter'
  post 'home/datesheet' => 'datesheets#datesheet_filter' , as: 'datesheet_filter'
  root 'home#home'
  get 'upload/index'
  get 'upload/uploadFile' 

  devise_for :users 

end

app/models/adminform.rb
class Adminform < ActiveRecord::Base
end

app/models/class_group.rb
class ClassGroup < ActiveRecord::Base
	belongs_to :student	
end

app/models/datafile.rb
class DataFile < ActiveRecord::Base
  def self.save(upload)
    name =  upload['datafile'].original_filename
    directory = "public/data"
    # create the file path
    path = File.join(directory, name)
    # write the file
    File.open(path, "wb") { |f| f.write(upload['datafile'].read) }
  end
end

app/models/datesheet.rb
class Datesheet < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/notice.rb
class Notice < ActiveRecord::Base
end

app/models/report.rb
class Report < ActiveRecord::Base
	belongs_to :student
end

app/models/student.rb
class Student < ActiveRecord::Base
	has_many :classgroups
	has_many :reports
	mount_uploader :stud_image, ImageUploader
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
	belongs_to :user
	validates :teacher_id, uniqueness: true
	has_attached_file :photo, :styles => { :small => "150x150>" }
    mount_uploader :image, ImageUploader 
	validates_attachment_content_type :photo, :content_type => ['image/jpg', 'image/png']
end

app/models/timetable.rb
class Timetable < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   GENDER_TYPES = [ ["Male","0"], [ "Female","1" ] ]
   validates_inclusion_of :is_female, in: [true, false]    
     
end

app/controllers/adminforms_controller.rb
class AdminformsController < ApplicationController
  before_action :set_adminform, only: [:show, :edit, :update, :destroy]

  # GET /adminforms
  # GET /adminforms.json
  def index
    @adminforms = Adminform.all
  end

  # GET /adminforms/1
  # GET /adminforms/1.json
  def show
  end

  # GET /adminforms/new
  def new
    @adminform = Adminform.new
  end

  # GET /adminforms/1/edit
  def edit
  end

  # POST /adminforms
  # POST /adminforms.json
  def create
    @adminform = Adminform.new(adminform_params)

    respond_to do |format|
      if @adminform.save
        format.html { redirect_to @adminform, notice: 'Adminform was successfully created.' }
        format.json { render :show, status: :created, location: @adminform }
      else
        format.html { render :new }
        format.json { render json: @adminform.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /adminforms/1
  # PATCH/PUT /adminforms/1.json
  def update
    respond_to do |format|
      if @adminform.update(adminform_params)
        format.html { redirect_to @adminform, notice: 'Adminform was successfully updated.' }
        format.json { render :show, status: :ok, location: @adminform }
      else
        format.html { render :edit }
        format.json { render json: @adminform.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /adminforms/1
  # DELETE /adminforms/1.json
  def destroy
    @adminform.destroy
    respond_to do |format|
      format.html { redirect_to adminforms_url, notice: 'Adminform was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_adminform
      @adminform = Adminform.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def adminform_params
      params.require(:adminform).permit(:Name_of_student, :Gender, :Class, :Date_of_birth, :Category, :Nationality, :Father_name, :Mother_name, :Address_line_1, :Address_line2, :City, :State, :Pin_code, :Email, :Phone, :Father_occupation, :Highest_degree_1, :Annual_income_1, :Mother_occupation, :Highest_degree_2, :Annual_income_2)
    end
end

app/helpers/adminforms_helper.rb
module AdminformsHelper
end

app/helpers/datesheets_helper.rb
module DatesheetsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/timetables_helper.rb
module TimetablesHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/views/adminforms/_form.html.erb
<%= form_for(@adminform) do |f| %>
  <% if @adminform.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@adminform.errors.count, "error") %> prohibited this adminform from being saved:</h2>

      <ul>
      <% @adminform.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :Name_of_student %><br>
    <%= f.text_field :Name_of_student %>
  </div>
  <div class="field">
         <%= f.radio_button :Gender, true %> <%= f.label :Gender, "Female" %>
          <%= f.radio_button :Gender, false %> <%= f.label :Gender, "Male" %>
  </div>
  <div class="field">
    <%= f.label :Class %><br>
    <%= f.number_field :Class %>
  </div>
  <div class="field">
    <%= f.label :Date_of_birth %><br>
    <%= f.datetime_select :Date_of_birth %>
  </div>
  <div class="field">
    <%= f.label :Category %><br>
    <%= f.radio_button :Category, "GEN" %><%= f.label :Category, "GEN" %>
    <%= f.radio_button :Category, "SC" %><%= f.label :Category, "SC" %>
    <%= f.radio_button :Category, "ST" %><%= f.label :Category, "ST" %>
  </div>
  <div class="field">
    <%= f.label :Nationality %><br>
    <%= f.text_field :Nationality %>
  </div>
  <div class="field">
    <%= f.label :Father_name %><br>
    <%= f.text_field :Father_name %>
  </div>
  <div class="field">
    <%= f.label :Mother_name %><br>
    <%= f.text_field :Mother_name %>
  </div>
  <div class="field">
    <%= f.label :Address_line_1 %><br>
    <%= f.text_field :Address_line_1 %>
  </div>
  <div class="field">
    <%= f.label :Address_line2 %><br>
    <%= f.text_field :Address_line2 %>
  </div>
  <div class="field">
    <%= f.label :City %><br>
    <%= f.text_field :City %>
  </div>
  <div class="field">
    <%= f.label :State %><br>
    <%= f.text_field :State %>
  </div>
  <div class="field">
    <%= f.label :Pin_code %><br>
    <%= f.number_field :Pin_code %>
  </div>
  <div class="field">
    <%= f.label :Email %><br>
    <%= f.email_field :Email %>
  </div>
  <div class="field">
    <%= f.label :Phone %><br>
    <%= f.phone_field :Phone %>
  </div>
  <div class="field">
    <%= f.label :Father_occupation %><br>
    <%= f.text_field :Father_occupation %>
  </div>
  <div class="field">
    <%= f.label :Highest_degree_1 %><br>
    <%= f.text_field :Highest_degree_1 %>
  </div>
  <div class="field">
    <%= f.label :Annual_income_1 %><br>
    <%= f.number_field :Annual_income_1 %>
  </div>
  <div class="field">
    <%= f.label :Mother_occupation %><br>
    <%= f.text_field :Mother_occupation %>
  </div>
  <div class="field">
    <%= f.label :Highest_degree_2 %><br>
    <%= f.text_field :Highest_degree_2 %>
  </div>
  <div class="field">
    <%= f.label :Annual_income_2 %><br>
    <%= f.number_field :Annual_income_2 %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/adminforms/edit.html.erb
<h1>Editing Adminform</h1>

<%= render 'form' %>

<%= link_to 'Show', @adminform %> |
<%= link_to 'Back', adminforms_path %>

app/views/adminforms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Adminforms</h1>

<table>
  <thead>
    <tr>
      <th>Name of student</th>
      <th>Gender</th>
      <th>Class</th>
      <th>Date of birth</th>
      <th>Category</th>
      <th>Nationality</th>
      <th>Father name</th>
      <th>Mother name</th>
      <th>Address line 1- string</th>
      <th>Address line2</th>
      <th>City</th>
      <th>State</th>
      <th>Pin code</th>
      <th>Email</th>
      <th>Phone</th>
      <th>Father occupation -string</th>
      <th>Highest degree 1</th>
      <th>Annual income 1</th>
      <th>Mother occupation</th>
      <th>Highest degree 2</th>
      <th>Annual income 2</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @adminforms.each do |adminform| %>
      <tr>
        <td><%= adminform.Name_of_student %></td>
        <td><%= adminform.Gender %></td>
        <td><%= adminform.Class %></td>
        <td><%= adminform.Date_of_birth %></td>
        <td><%= adminform.Category %></td>
        <td><%= adminform.Nationality %></td>
        <td><%= adminform.Father_name %></td>
        <td><%= adminform.Mother_name %></td>
        <td><%= adminform.Address_line_1-_string %></td>
        <td><%= adminform.Address_line2 %></td>
        <td><%= adminform.City %></td>
        <td><%= adminform.State %></td>
        <td><%= adminform.Pin_code %></td>
        <td><%= adminform.Email %></td>
        <td><%= adminform.Phone %></td>
        <td><%= adminform.Father_occupation_-string %></td>
        <td><%= adminform.Highest_degree_1 %></td>
        <td><%= adminform.Annual_income_1 %></td>
        <td><%= adminform.Mother_occupation %></td>
        <td><%= adminform.Highest_degree_2 %></td>
        <td><%= adminform.Annual_income_2 %></td>
        <td><%= link_to 'Show', adminform %></td>
        <td><%= link_to 'Edit', edit_adminform_path(adminform) %></td>
        <td><%= link_to 'Destroy', adminform, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Adminform', new_adminform_path %>

app/views/adminforms/new.html.erb
<h1>New Adminform</h1>

<%= render 'form' %>

<%= link_to 'Back', adminforms_path %>

app/views/adminforms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name of student:</strong>
  <%= @adminform.Name_of_student %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @adminform.Gender %>
</p>

<p>
  <strong>Class:</strong>
  <%= @adminform.Class %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @adminform.Date_of_birth %>
</p>

<p>
  <strong>Category:</strong>
  <%= @adminform.Category %>
</p>

<p>
  <strong>Nationality:</strong>
  <%= @adminform.Nationality %>
</p>

<p>
  <strong>Father name:</strong>
  <%= @adminform.Father_name %>
</p>

<p>
  <strong>Mother name:</strong>
  <%= @adminform.Mother_name %>
</p>

<p>
  <strong>Address line 1:</strong>
  <%= @adminform.Address_line_1 %>
</p>

<p>
  <strong>Address line2:</strong>
  <%= @adminform.Address_line2 %>
</p>

<p>
  <strong>City:</strong>
  <%= @adminform.City %>
</p>

<p>
  <strong>State:</strong>
  <%= @adminform.State %>
</p>

<p>
  <strong>Pin code:</strong>
  <%= @adminform.Pin_code %>
</p>

<p>
  <strong>Email:</strong>
  <%= @adminform.Email %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @adminform.Phone %>
</p>

<p>
  <strong>Father occupation :</strong>
  <%= @adminform.Father_occupation %>
</p>

<p>
  <strong>Highest degree 1:</strong>
  <%= @adminform.Highest_degree_1 %>
</p>

<p>
  <strong>Annual income 1:</strong>
  <%= @adminform.Annual_income_1 %>
</p>

<p>
  <strong>Mother occupation:</strong>
  <%= @adminform.Mother_occupation %>
</p>

<p>
  <strong>Highest degree 2:</strong>
  <%= @adminform.Highest_degree_2 %>
</p>

<p>
  <strong>Annual income 2:</strong>
  <%= @adminform.Annual_income_2 %>
</p>

<%= link_to 'Edit', edit_adminform_path(@adminform) %> |
<%= link_to 'Back', adminforms_path %>