config/routes.rb
Rails.application.routes.draw do
  resources :reports
  resources :datesheets
  resources :students do
    resources :reports
  end  
  resources :class_groups
  resources :teachers
  resources :timetables
  resources :adminforms
  resources :notices
  resources :events
  get 'home/home'
  get 'home/transport'
  get 'home/admission'
  get 'home/timetable' 
  get 'home/datesheet' 
  get 'home/teacher' 
  post 'home/timetable' => 'timetables#class_filter' , as: 'class_filter'
  post 'home/datesheet' => 'datesheets#datesheet_filter' , as: 'datesheet_filter'
  root 'home#home'
  get 'upload/index'
  get 'upload/uploadFile' 

  devise_for :users 

end

app/models/adminform.rb
class Adminform < ActiveRecord::Base
end

app/models/class_group.rb
class ClassGroup < ActiveRecord::Base
	belongs_to :student	
end

app/models/datafile.rb
class DataFile < ActiveRecord::Base
  def self.save(upload)
    name =  upload['datafile'].original_filename
    directory = "public/data"
    # create the file path
    path = File.join(directory, name)
    # write the file
    File.open(path, "wb") { |f| f.write(upload['datafile'].read) }
  end
end

app/models/datesheet.rb
class Datesheet < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/notice.rb
class Notice < ActiveRecord::Base
end

app/models/report.rb
class Report < ActiveRecord::Base
	belongs_to :student
end

app/models/student.rb
class Student < ActiveRecord::Base
	has_many :classgroups
	has_many :reports
	mount_uploader :stud_image, ImageUploader
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
	belongs_to :user
	validates :teacher_id, uniqueness: true
	has_attached_file :photo, :styles => { :small => "150x150>" }
    mount_uploader :image, ImageUploader 
	validates_attachment_content_type :photo, :content_type => ['image/jpg', 'image/png']
end

app/models/timetable.rb
class Timetable < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   GENDER_TYPES = [ ["Male","0"], [ "Female","1" ] ]
   validates_inclusion_of :is_female, in: [true, false]    
     
end

app/controllers/teachers_controller.rb
class TeachersController < ApplicationController
  before_action :set_teacher, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user! , only: [:edit, :new, :destroy]
  

  # GET /teachers
  # GET /teachers.json
  def index
    @teachers = Teacher.all
  end

  # GET /teachers/1
  # GET /teachers/1.json
  def show
  end

  # GET /teachers/new
  def new
    @teacher = Teacher.new
  end

  # GET /teachers/1/edit
  def edit
  end

  # POST /teachers
  # POST /teachers.json
  def create
    @teacher = Teacher.new(teacher_params)
    @teacher.teacher_id = current_user.id
    respond_to do |format|
      if @teacher.save
        format.html { redirect_to @teacher, notice: 'Teacher was successfully created.' }
        format.json { render :show, status: :created, location: @teacher }
      else
        format.html { render :new }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teachers/1
  # PATCH/PUT /teachers/1.json
  def update
    respond_to do |format|
      if @teacher.update(teacher_params)
        format.html { redirect_to @teacher, notice: 'Teacher was successfully updated.' }
        format.json { render :show, status: :ok, location: @teacher }
      else
        format.html { render :edit }
        format.json { render json: @teacher.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teachers/1
  # DELETE /teachers/1.json
  def destroy
    @teacher.destroy
    respond_to do |format|
      format.html { redirect_to teachers_url, notice: 'Teacher was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_teacher
      @teacher = Teacher.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def teacher_params
      params.require(:teacher).permit(:teacher_id, :about_me, :image)
    end
end

app/helpers/adminforms_helper.rb
module AdminformsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/datesheets_helper.rb
module DatesheetsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/timetables_helper.rb
module TimetablesHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/views/teachers/_form.html.erb
<%= form_for @teacher, :html => { :multipart => true } do |f| %>
  <% if @teacher.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@teacher.errors.count, "error") %> prohibited this teacher from being saved:</h2>

      <ul>
      <% @teacher.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    
    <%= f.file_field :image %>
  </div>
  <div class="field">
    <%= f.label :about_me %><br>
    <%= f.text_area :about_me %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/teachers/edit.html.erb
<h1>Editing Teacher</h1>

<%= render 'form' %>

<%= link_to 'Show', @teacher %> |
<%= link_to 'Back', teachers_path %>

app/views/teachers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Teachers</h1>

<table>
  <thead>
    <tr>
      <th>Teacher</th>
      <th>  </th>
      <th>About me</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @teachers.each do |teacher| %>
      <tr>
        <td><%= image_tag teacher.image_url(:thumb) %></td>
        <td>  </td>
        <td><%= simple_format(teacher.about_me) %></td>
        <td><%= link_to 'Show', teacher %></td>
        <td><%= link_to 'Edit', edit_teacher_path(teacher) %></td>
        <td><%= link_to 'Destroy', teacher, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
      
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Teacher', new_teacher_path %>

app/views/teachers/new.html.erb
<h1>New Teacher</h1>

<%= render 'form' %>

<%= link_to 'Back', teachers_path %>

app/views/teachers/show.html.erb
<p id="notice"><%= notice %></p>

<div class="row">
<div class="col-sm-2">
<%= image_tag @teacher.image_url(:thumb) %>
<p>
  <strong>Teacher:</strong>
  <%= @teacher.teacher_id %>
</p>
</div>
<div offset = "col-sm-offset-2">
<p>
  <strong>About me:</strong>
  <%= simple_format(@teacher.about_me) %>
</p>
</div>
</div>

<%= link_to 'Edit', edit_teacher_path(@teacher) %> |
<%= link_to 'Back', teachers_path %>