config/routes.rb
Rails.application.routes.draw do
  resources :reports
  resources :datesheets
  resources :students do
    resources :reports
  end  
  resources :class_groups
  resources :teachers
  resources :timetables
  resources :adminforms
  resources :notices
  resources :events
  get 'home/home'
  get 'home/transport'
  get 'home/admission'
  get 'home/timetable' 
  get 'home/datesheet' 
  get 'home/teacher' 
  post 'home/timetable' => 'timetables#class_filter' , as: 'class_filter'
  post 'home/datesheet' => 'datesheets#datesheet_filter' , as: 'datesheet_filter'
  root 'home#home'
  get 'upload/index'
  get 'upload/uploadFile' 

  devise_for :users 

end

app/models/adminform.rb
class Adminform < ActiveRecord::Base
end

app/models/class_group.rb
class ClassGroup < ActiveRecord::Base
	belongs_to :student	
end

app/models/datafile.rb
class DataFile < ActiveRecord::Base
  def self.save(upload)
    name =  upload['datafile'].original_filename
    directory = "public/data"
    # create the file path
    path = File.join(directory, name)
    # write the file
    File.open(path, "wb") { |f| f.write(upload['datafile'].read) }
  end
end

app/models/datesheet.rb
class Datesheet < ActiveRecord::Base
end

app/models/event.rb
class Event < ActiveRecord::Base
end

app/models/notice.rb
class Notice < ActiveRecord::Base
end

app/models/report.rb
class Report < ActiveRecord::Base
	belongs_to :student
end

app/models/student.rb
class Student < ActiveRecord::Base
	has_many :classgroups
	has_many :reports
	mount_uploader :stud_image, ImageUploader
end

app/models/teacher.rb
class Teacher < ActiveRecord::Base
	belongs_to :user
	validates :teacher_id, uniqueness: true
	has_attached_file :photo, :styles => { :small => "150x150>" }
    mount_uploader :image, ImageUploader 
	validates_attachment_content_type :photo, :content_type => ['image/jpg', 'image/png']
end

app/models/timetable.rb
class Timetable < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   GENDER_TYPES = [ ["Male","0"], [ "Female","1" ] ]
   validates_inclusion_of :is_female, in: [true, false]    
     
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  before_action :set_report, only: [:show, :edit, :update, :destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show
  end

  # GET /reports/new
  def new
    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
  end

  # POST /reports
  # POST /reports.json
  def create
    @student = Student.find(params[:student_id])
    @report = @student.reports.create(report_params)

    respond_to do |format|
      if @report.save
        format.html { redirect_to @student, notice: 'Report was successfully created.' }
        format.json { render :show, status: :created, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(report_params)
        format.html { redirect_to @report, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_report
      @report = Report.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def report_params
      params.require(:report).permit(:student_id, :class_name, :class_year, :exam_name, :subject_1, :marks_1, :subject_2, :marks_2, :subject_3, :marks_3, :subject_4, :marks_4, :subject_5, :marks_5, :subject_6, :marks_6, :subject_7, :marks_7, :subject_8, :marks_8, :subject_9, :marks_9, :subject_10, :marks_10, :comment, :rank)
    end
end

app/helpers/adminforms_helper.rb
module AdminformsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/datesheets_helper.rb
module DatesheetsHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/notices_helper.rb
module NoticesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/helpers/students_helper.rb
module StudentsHelper
end

app/helpers/teachers_helper.rb
module TeachersHelper
end

app/helpers/timetables_helper.rb
module TimetablesHelper
end

app/helpers/upload_helper.rb
module UploadHelper
end

app/views/reports/_form.html.erb
<%= form_for(@report) do |f| %>
  <% if @report.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@report.errors.count, "error") %> prohibited this report from being saved:</h2>

      <ul>
      <% @report.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :student_id %><br>
    <%= f.number_field :student_id %>
  </div>
  <div class="field">
    <%= f.label :class_name %><br>
    <%= f.text_field :class_name %>
  </div>
  <div class="field">
    <%= f.label :class_year %><br>
    <%= f.number_field :class_year %>
  </div>
  <div class="field">
    <%= f.label :exam_name %><br>
    <%= f.text_field :exam_name %>
  </div>
  <div class="field">
    <%= f.label :subject_1 %><br>
    <%= f.text_field :subject_1 %>
  </div>
  <div class="field">
    <%= f.label :marks_1 %><br>
    <%= f.number_field :marks_1 %>
  </div>
  <div class="field">
    <%= f.label :subject_2 %><br>
    <%= f.text_field :subject_2 %>
  </div>
  <div class="field">
    <%= f.label :marks_2 %><br>
    <%= f.number_field :marks_2 %>
  </div>
  <div class="field">
    <%= f.label :subject_3 %><br>
    <%= f.text_field :subject_3 %>
  </div>
  <div class="field">
    <%= f.label :marks_3 %><br>
    <%= f.number_field :marks_3 %>
  </div>
  <div class="field">
    <%= f.label :subject_4 %><br>
    <%= f.text_field :subject_4 %>
  </div>
  <div class="field">
    <%= f.label :marks_4 %><br>
    <%= f.number_field :marks_4 %>
  </div>
  <div class="field">
    <%= f.label :subject_5 %><br>
    <%= f.text_field :subject_5 %>
  </div>
  <div class="field">
    <%= f.label :marks_5 %><br>
    <%= f.number_field :marks_5 %>
  </div>
  <div class="field">
    <%= f.label :subject_6 %><br>
    <%= f.text_field :subject_6 %>
  </div>
  <div class="field">
    <%= f.label :marks_6 %><br>
    <%= f.number_field :marks_6 %>
  </div>
  <div class="field">
    <%= f.label :subject_7 %><br>
    <%= f.text_field :subject_7 %>
  </div>
  <div class="field">
    <%= f.label :marks_7 %><br>
    <%= f.number_field :marks_7 %>
  </div>
  <div class="field">
    <%= f.label :subject_8 %><br>
    <%= f.text_field :subject_8 %>
  </div>
  <div class="field">
    <%= f.label :marks_8 %><br>
    <%= f.number_field :marks_8 %>
  </div>
  <div class="field">
    <%= f.label :subject_9 %><br>
    <%= f.text_field :subject_9 %>
  </div>
  <div class="field">
    <%= f.label :marks_9 %><br>
    <%= f.number_field :marks_9 %>
  </div>
  <div class="field">
    <%= f.label :subject_10 %><br>
    <%= f.text_field :subject_10 %>
  </div>
  <div class="field">
    <%= f.label :marks_10 %><br>
    <%= f.number_field :marks_10 %>
  </div>
  <div class="field">
    <%= f.label :comment %><br>
    <%= f.text_field :comment %>
  </div>
  <div class="field">
    <%= f.label :rank %><br>
    <%= f.number_field :rank %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/reports/_report.html.erb
  <%= div_for report do %>
      <p >
        <strong>Posted <%= time_ago_in_words(report.created_at)%></strong><br/>
        <%= h(report.exam_name) %>

      </p>
  <% end %>

app/views/reports/edit.html.erb
<h1>Editing Report</h1>

<%= render 'form' %>

<%= link_to 'Show', @report %> |
<%= link_to 'Back', reports_path %>

app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Reports</h1>

<table>
  <thead>
    <tr>
      <th>Student</th>
      <th>Class name</th>
      <th>Class year</th>
      <th>Exam name</th>
      <th>Subject 1</th>
      <th>Marks 1</th>
      <th>Subject 2</th>
      <th>Marks 2</th>
      <th>Subject 3</th>
      <th>Marks 3</th>
      <th>Subject 4</th>
      <th>Marks 4</th>
      <th>Subject 5</th>
      <th>Marks 5</th>
      <th>Subject 6</th>
      <th>Marks 6</th>
      <th>Subject 7</th>
      <th>Marks 7</th>
      <th>Subject 8</th>
      <th>Marks 8</th>
      <th>Subject 9</th>
      <th>Marks 9</th>
      <th>Subject 10</th>
      <th>Marks 10</th>
      <th>Comment</th>
      <th>Rank</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td><%= report.student_id %></td>
        <td><%= report.class_name %></td>
        <td><%= report.class_year %></td>
        <td><%= report.exam_name %></td>
        <td><%= report.subject_1 %></td>
        <td><%= report.marks_1 %></td>
        <td><%= report.subject_2 %></td>
        <td><%= report.marks_2 %></td>
        <td><%= report.subject_3 %></td>
        <td><%= report.marks_3 %></td>
        <td><%= report.subject_4 %></td>
        <td><%= report.marks_4 %></td>
        <td><%= report.subject_5 %></td>
        <td><%= report.marks_5 %></td>
        <td><%= report.subject_6 %></td>
        <td><%= report.marks_6 %></td>
        <td><%= report.subject_7 %></td>
        <td><%= report.marks_7 %></td>
        <td><%= report.subject_8 %></td>
        <td><%= report.marks_8 %></td>
        <td><%= report.subject_9 %></td>
        <td><%= report.marks_9 %></td>
        <td><%= report.subject_10 %></td>
        <td><%= report.marks_10 %></td>
        <td><%= report.comment %></td>
        <td><%= report.rank %></td>
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_report_path %>

app/views/reports/new.html.erb
<h1>New Report</h1>

<%= render 'form' %>

<%= link_to 'Back', reports_path %>

app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

    <p >
      <strong>Student:</strong>
      <%= @report.student_id %>
    </p>

    <p >
      <strong>Class name:</strong>
      <%= @report.class_name %>
    </p>

    <p >
      <strong>Class year:</strong>
      <%= @report.class_year %>
    </p>

    <p >
      <strong>Exam name:</strong>
      <%= @report.exam_name %>
    </p>
<div align="center">
<table class="table">
<thead>
<tr>
<th> Subject </th>
<th> Marks </th>
</tr></thead>
<tbody>
<tr>
 <td> <%= @report.subject_1 %> </td>
 <td> <%= @report.marks_1 %>  </td>
</tr> 
<tr>
 <td> <%= @report.subject_1 %> </td>
 <td> <%= @report.marks_1 %>  </td>
</tr> 
<tr>
 <td> <%= @report.subject_2 %> </td>
 <td> <%= @report.marks_2%>  </td>
</tr> 
<tr>
 <td> <%= @report.subject_3 %> </td>
 <td> <%= @report.marks_3 %>  </td>
</tr> 
<tr>
 <td> <%= @report.subject_4 %> </td>
 <td> <%= @report.marks_4 %>  </td>
</tr> 
<tr>
 <td> <%= @report.subject_5 %> </td>
 <td> <%= @report.marks_5 %>  </td>
</tr> 
<tr>
 <td> <%= @report.subject_6 %> </td>
 <td> <%= @report.marks_6 %>  </td>
</tr> 
<tr>
 <td> <%= @report.subject_7 %> </td>
 <td> <%= @report.marks_7 %>  </td>
</tr> 
<tr>
 <td> <%= @report.subject_8 %> </td>
 <td> <%= @report.marks_8 %>  </td>
</tr> 
<tr>
 <td> <%= @report.subject_9 %> </td>
 <td> <%= @report.marks_9 %>  </td>
</tr> 
<tr>
 <td> <%= @report.subject_10 %> </td>
 <td> <%= @report.marks_10 %>  </td>
</tr> 

<p>
  <strong>Comment:</strong>
  <%= @report.comment %>
</p>

<p>
  <strong>Rank:</strong>
  <%= @report.rank %>
</p>
</tbody>
</table>
</div>
<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>